### ISSUE TITLE
Status -1 even if game is live .

### ISSUE THREAD

**Issue by rajangupta24** [xKairu/MLG.tv-API#1]
I tried http://streamapi.majorleaguegaming.com/service/streams/status/xyz , even if xyz in live its returning status = -1 in data response. 

Is this api in in working condition .?

**Comment by kylekz** [comment]
![capture](https://cloud.githubusercontent.com/assets/450516/6885156/5c8a7356-d66f-11e4-9996-936fdd79e06b.PNG)

Works for me man. Can you show me your code?
